### ISSUE TITLE
Float menu initialization

### ISSUE THREAD

**Issue by rbtylee** [thewaiter/Clipboard#2]
After module is loaded but no gadgets added anywhere float menu is not initialized properly. History if any is read but if clipboard contains any item it is not added. I have been aware of this for a while. Also maybe related is float menu does not appear to function correctly until gadget is added.

**Comment by thewaiter** [comment]
Hmm, maybe we should add loading history to e_modapi_init instead of gc_init...

**Comment by rbtylee** [comment]
Currently history is read in _cb_show_menu and  that works for float. However it does not add current clipboard item to menu with no gadgets added. Nor will it add any future clipboard items to float menu without a gadget present.

This issue is a show breaker for our float menu implementation and our 'beta' release. I have been giving this some thought and my conclusions right or wrong:

The reason float does not work with no gadgets is because of the code in _gc_init:

```
 E_LIST_HANDLER_APPEND(inst->handle, ECORE_X_EVENT_SELECTION_NOTIFY, _cb_event_selection, inst);

  /* Ensure our gadget is initialized to current clipboard contents */
  ecore_x_selection_clipboard_request(inst->win, ECORE_X_SELECTION_TARGET_UTF8_STRING);

  inst->check_timer = ecore_timer_add(TIMEOUT_1, _cb_clipboard_request, inst);
```
Neither _cb_event_selection or _cb_clipboard_request have been set up for float_list in e_modapi_init.

Attempts to do so is problematic as ecore_x_selection_clipboard_request present in function _cb_clipboard_request seems to need a Ecore_X_Window in order to function correctly.

 A naive attempt to pass enlightenments root window here fail. (see the function ecore_x_window_root_first_get).

This comment is to let you know I have been attempting to find a hack/fix/solution for this issue...

**Comment by rbtylee** [comment]
I think this issue should be resolved now. Time to move on to other issues and other things. If not reopen and comment please ...
