### ISSUE TITLE
updating clipboard - X issue

### ISSUE THREAD

**Issue by thewaiter** [thewaiter/Clipboard#4]
Open leafpad, write some text there, copy it and close leafpad. The content is inside the our Clipboard module saved but when you just paste, nothing happens. When I click to the menu item and paste, it works... This is well known X issue but parcellite solves it. I'd love to see solved this in our project this one as well.

**Comment by thewaiter** [comment]
Suggestion: every TIMEOUT_1 call _cb_menu_item for the current item. Simply, emulate pressing menu item...Just a theory :)

**Comment by rbtylee** [comment]
Should be fix for now with  _**commit ecbbdb2: Gain ownership of added clipboard items**_
