### ISSUE TITLE
Thunar unable to paste files when module is loaded

### ISSUE THREAD

**Issue by rbtylee** [thewaiter/Clipboard#8]
name explains it all, but if our module is loaded then you can not copy and paste files to a different location in thunar.

**Comment by rbtylee** [comment]
Ok the weird thing is for me it all works fine when running under Xephyr. Not sure why but since that is way I test and debug things perhaps i need rethink that.

**Comment by rbtylee** [comment]
@thewaiter, we can close this once you verify commit above does indeed fix this for you without introducing any additional issues.

**Comment by thewaiter** [comment]
Fantastic Robert. It does work. Great job as usual :)
